### ISSUE TITLE
Incompatible with version 2024.1 of IDEA.

### ISSUE THREAD

**Issue by nickfan** [aliyun/alibabacloud-api-jetbrains-toolkit#36]
Incompatible with version 2024.1 of IDEA.

![image](https://github.com/aliyun/alibabacloud-api-jetbrains-toolkit/assets/100613/e3dc58fc-3ed5-4367-9ed4-4bc2b8c85420)

**Comment by PanPanZou** [comment]
Thank you for your attention. A new version will be released in 4.19 to support version 2024.1.

**Comment by PanPanZou** [comment]
Hello, the Alibaba Cloud Developer Toolkit plugin has released a new version 0.0.6 yesterday to support version 24.1 IDE: https://plugins.jetbrains.com/plugin/23361-alibaba-cloud-developer-toolkit/ versions/stable. Welcome to experience!

**Comment by PanPanZou** [comment]
Hello, the Alibaba Cloud Developer Toolkit plugin has released a new version 0.0.6 yesterday to support version 24.1 IDE: https://plugins.jetbrains.com/plugin/23361-alibaba-cloud-developer-toolkit/ versions/stable. Welcome to experience!
