### ISSUE TITLE
Request for an Englisch version of the plugin

### ISSUE THREAD

**Issue by MarcManz-1** [aliyun/alibabacloud-api-jetbrains-toolkit#43]
Hi,

Do plan to have an English version of the plugin? 

<img width="349" alt="image" src="https://github.com/aliyun/alibabacloud-api-jetbrains-toolkit/assets/132681268/af23f17c-756d-4d92-928a-6551e610215c">

This would be very helpful for my development tasks.

**Comment by PanPanZou** [comment]
Thanks for attention! The English version is being scheduled.

**Comment by PanPanZou** [comment]
Sorry for the wait. The English version of the plugin has been released. Please update to version 0.0.13 to use it.
